# Site settings
title: Josué García Yza
email: osueboy@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing about web's new technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://osueboy.github.io" # the base hostname & protocol for your site
twitter_username: osueboy
github_username:  osueboy

# Build settings
markdown: kramdown
